// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PandaPocket.Services.Invoice.Persistence;

#nullable disable

namespace PandaPocket.Services.Invoice.Persistence.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20260825230225_SnakeCaseColumnNames")]
    partial class SnakeCaseColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PandaPocket.Services.Invoice.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountZar")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_zar");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CryptoAmount")
                        .HasColumnType("numeric(24,8)")
                        .HasColumnName("crypto_amount");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("LockedRate")
                        .HasColumnType("numeric(24,8)")
                        .HasColumnName("locked_rate");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("PayToAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pay_to_address");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("MerchantId", "CreatedAt")
                        .HasDatabaseName("ix_invoices_merchant_created");

                    b.HasIndex("MerchantId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_merchant_reference");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_invoices_status_expires");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("PandaPocket.Services.Invoice.Domain.InvoiceStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_invoice_status_history");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_status_history_correlation");

                    b.HasIndex("InvoiceId", "CreatedAt")
                        .HasDatabaseName("ix_status_history_invoice_created");

                    b.ToTable("invoice_status_history", (string)null);
                });

            modelBuilder.Entity("PandaPocket.Services.Invoice.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountCrypto")
                        .HasColumnType("numeric(24,8)")
                        .HasColumnName("amount_crypto");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.HasIndex("TxHash")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_tx_hash");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("PandaPocket.Services.Invoice.Domain.InvoiceStatusHistory", b =>
                {
                    b.HasOne("PandaPocket.Services.Invoice.Domain.Invoice", "Invoice")
                        .WithMany("History")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_status_history_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PandaPocket.Services.Invoice.Domain.Payment", b =>
                {
                    b.HasOne("PandaPocket.Services.Invoice.Domain.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PandaPocket.Services.Invoice.Domain.Invoice", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
