// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PandaPocket.Services.Settlement.Persistence;

#nullable disable

namespace PandaPocket.Services.Settlement.Persistence.Migrations
{
    [DbContext(typeof(SettlementDbContext))]
    partial class SettlementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PandaPocket.Services.Settlement.Domain.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountZar")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_zar");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entry_type");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("InvoiceId", "EntryType")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_invoice_entrytype")
                        .HasFilter("invoice_id IS NOT NULL");

                    b.HasIndex("MerchantId", "CreatedAt")
                        .HasDatabaseName("ix_ledger_merchant_created");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("PandaPocket.Services.Settlement.Domain.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("last_status_code");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_webhook_deliveries");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_webhook_merchant");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_webhook_status_next_attempt");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("PandaPocket.Services.Settlement.Persistence.MerchantBalance", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<decimal>("AvailableZar")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available_zar");

                    b.Property<decimal>("LifetimeCreditedZar")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("lifetime_credited_zar");

                    b.Property<decimal>("LifetimeFeesZar")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("lifetime_fees_zar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MerchantId")
                        .HasName("pk_merchant_balances");

                    b.ToTable("merchant_balances", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
