// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PandaPocket.Services.Soc.Persistence;

#nullable disable

namespace PandaPocket.Services.Soc.Persistence.Migrations
{
    [DbContext(typeof(SocDbContext))]
    [Migration("20260929104920_InitialSocSchema")]
    partial class InitialSocSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PandaPocket.Services.Soc.Persistence.SocEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AffectedEntity")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("affected_entity");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("endpoint");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_ip");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EventId")
                        .HasName("pk_soc_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_soc_events_correlation");

                    b.HasIndex("EventType", "Timestamp")
                        .HasDatabaseName("ix_soc_events_type_time");

                    b.HasIndex("SourceIp", "Timestamp")
                        .HasDatabaseName("ix_soc_events_source_time");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("ix_soc_events_user_time");

                    b.ToTable("soc_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
